spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 369d46036a7ce401b18d
            clientSecret: 5f3db0afe58feb696fb91ac16c06b27677a19b4f
            scope: oidc
  profiles:
    active: development
  datasource:
    generate-unique-name: false
    name: cantvas
    url: jdbc:h2:mem:cantvas
server:
  error:
    whitelabel:
      enabled: false
    path: /error